# Generated by Django 3.1.4 on 2020-12-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondtech_app', '0002_device_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('Smartphone', 'Smartphone'), ('Tablet', 'Tablet'), ('Laptop', 'Laptop')], max_length=10),
        ),
    ]
